create or replace function public.create_company(p_company jsonb)
returns table (id uuid, display_name text)
language plpgsql security definer set search_path = public, auth, extensions
as $$
declare v_company public.companies; v_tax_id text := regexp_replace(coalesce(p_company->>'tax_id', ''), '\D', '', 'g'); v_state text := upper(btrim(coalesce(p_company->>'fiscal_state', ''))); v_postal text := regexp_replace(coalesce(p_company->>'fiscal_postal_code', ''), '\D', '', 'g');
begin
  if not exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'PLATFORM_ADMIN' and p.status = 'ACTIVE') then raise exception 'FORBIDDEN'; end if;
  if nullif(btrim(p_company->>'legal_name'), '') is null or nullif(btrim(p_company->>'display_name'), '') is null or length(v_tax_id) <> 14 or v_state !~ '^[A-Z]{2}$' or length(v_postal) <> 8 or nullif(btrim(p_company->>'corporate_email'), '') is null or nullif(btrim(p_company->>'fiscal_address_line'), '') is null or nullif(btrim(p_company->>'fiscal_address_number'), '') is null or nullif(btrim(p_company->>'fiscal_district'), '') is null or nullif(btrim(p_company->>'fiscal_city'), '') is null or nullif(btrim(p_company->>'legal_representative_name'), '') is null or nullif(btrim(p_company->>'legal_representative_email'), '') is null or nullif(btrim(p_company->>'operational_contact_name'), '') is null or nullif(btrim(p_company->>'operational_contact_email'), '') is null then raise exception 'INVALID_COMPANY_DATA'; end if;
  insert into public.companies (legal_name, display_name, status, tax_id, state_registration, corporate_email, corporate_phone, fiscal_address_line, fiscal_address_number, fiscal_address_complement, fiscal_district, fiscal_city, fiscal_state, fiscal_postal_code, legal_representative_name, legal_representative_email, legal_representative_phone, operational_contact_name, operational_contact_email, operational_contact_phone, payment_terms_days, credit_limit_minor)
  values (btrim(p_company->>'legal_name'), btrim(p_company->>'display_name'), 'ACTIVE', v_tax_id, nullif(btrim(p_company->>'state_registration'), ''), lower(btrim(p_company->>'corporate_email')), nullif(btrim(p_company->>'corporate_phone'), ''), btrim(p_company->>'fiscal_address_line'), btrim(p_company->>'fiscal_address_number'), nullif(btrim(p_company->>'fiscal_address_complement'), ''), btrim(p_company->>'fiscal_district'), btrim(p_company->>'fiscal_city'), v_state, v_postal, btrim(p_company->>'legal_representative_name'), lower(btrim(p_company->>'legal_representative_email')), nullif(btrim(p_company->>'legal_representative_phone'), ''), btrim(p_company->>'operational_contact_name'), lower(btrim(p_company->>'operational_contact_email')), nullif(btrim(p_company->>'operational_contact_phone'), ''), greatest(coalesce((p_company->>'payment_terms_days')::integer, 0), 0), greatest(coalesce((p_company->>'credit_limit_minor')::bigint, 0), 0)) returning * into v_company;
  return query select v_company.id, v_company.display_name;
exception when unique_violation then raise exception 'COMPANY_ALREADY_EXISTS';
end; $$;
